spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grmr?&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
    defer-datasource-initialization: true

